import React from 'react';
const money = (v) => `₩${Number(v || 0).toLocaleString('ko-KR', { maximumFractionDigits: 0 })}`;
function Card({ title, children, wide = false }) { return <section className={`dashboard-card ${wide ? 'wide' : ''}`} style={{ ...styles.card, gridColumn: wide ? '1 / -1' : undefined }}><div style={styles.cardTitle}>{title}</div>{children}</section>; }
function Metric({ label, value, danger = false }) { return <div style={styles.metric}><span style={styles.label}>{label}</span><strong style={{ color: danger ? '#F87171' : '#F8FAFC' }}>{value}</strong></div>; }
function Button({ children, onClick, danger = false }) { return <button type="button" className="dashboard-btn" onClick={onClick} style={{ ...styles.button, ...(danger ? styles.danger : {}) }}>{children}</button>; }
export default function VirtualBrokerPanel({ state, sendCommand }) {
  const account = state.broker?.account || {};
  const broker = state.broker || {};
  const risk = state.risk || {};
  const positions = state.positions || {};
  const orders = state.orders || [];
  const executions = state.executions || [];
  const command = (action, payload = {}) => sendCommand({ action, ...payload });
  return <div className="dashboard-grid" style={styles.grid}>
    <Card title="Broker Status"><div className="dashboard-metrics-grid" style={styles.metrics}><Metric label="Mode" value={broker.mode || 'PAPER'} /><Metric label="Connection" value={broker.connected === false ? 'DISCONNECTED' : 'CONNECTED'} danger={broker.connected === false} /><Metric label="Order State" value={broker.order_state || 'NORMAL'} /><Metric label="Execution State" value={broker.execution_state || 'NORMAL'} /></div></Card>
    <Card title="Account / Margin"><div className="dashboard-metrics-grid" style={styles.metrics}><Metric label="Balance" value={money(account.balance)} /><Metric label="Realized PnL" value={money(account.realized_pnl)} /><Metric label="Unrealized PnL" value={money(account.unrealized_pnl)} /><Metric label="Used Margin" value={money(account.used_margin)} /><Metric label="Free Margin" value={money(account.free_margin)} /><Metric label="Margin Ratio" value={`${Number(account.margin_ratio || 0).toFixed(1)}%`} danger={Number(account.margin_ratio || 100) < 30} /></div></Card>
    <Card title="Margin Control"><div className="dashboard-control-row" style={styles.controlRow}><Button onClick={() => command('set_margin_mode', { mode: 'NORMAL' })}>정상</Button><Button onClick={() => command('set_margin_mode', { mode: 'TIGHT' })}>증거금 강화</Button><Button danger onClick={() => command('inject_margin_call')}>Margin Call</Button><Button danger onClick={() => command('inject_margin_shortage')}>증거금 부족</Button></div><div className="dashboard-control-row" style={styles.controlRow}><Button onClick={() => command('set_leverage', { leverage: 1 })}>1x</Button><Button onClick={() => command('set_leverage', { leverage: 2 })}>2x</Button><Button onClick={() => command('set_leverage', { leverage: 5 })}>5x</Button><Button onClick={() => command('set_leverage', { leverage: 10 })}>10x</Button></div></Card>
    <Card title="Communication / Execution Control"><div className="dashboard-control-row" style={styles.controlRow}><Button onClick={() => command('set_broker_connection', { connected: true })}>통신 정상</Button><Button danger onClick={() => command('set_broker_connection', { connected: false })}>통신 두절</Button><Button onClick={() => command('set_broker_latency', { latency_ms: 500 })}>500ms 지연</Button><Button onClick={() => command('set_broker_latency', { latency_ms: 0 })}>지연 해제</Button></div><div className="dashboard-control-row" style={styles.controlRow}><Button onClick={() => command('set_execution_behavior', { mode: 'NORMAL' })}>정상 체결</Button><Button onClick={() => command('set_execution_behavior', { mode: 'DELAYED' })}>체결 지연</Button><Button danger onClick={() => command('set_execution_behavior', { mode: 'REJECT' })}>주문 거부</Button></div></Card>
    <Card title="Positions">{Object.keys(positions).length ? <div className="dashboard-list" style={styles.list}>{Object.entries(positions).map(([key, value]) => <div key={key} className="dashboard-row" style={styles.row}><span>{key}</span><strong>{JSON.stringify(value)}</strong></div>)}</div> : <div style={styles.muted}>포지션 없음</div>}</Card>
    <Card title="Orders / Executions"><div style={styles.sectionLabel}>Orders</div><div className="dashboard-list" style={styles.list}>{orders.slice(-8).map((o, i) => <div key={i} className="dashboard-row" style={styles.row}><span>{o.track_id || o.client_order_id || '-'}</span><span>{o.side || ''} {o.qty || ''}</span></div>)}{!orders.length && <div style={styles.muted}>주문 없음</div>}</div><div style={{ ...styles.sectionLabel, marginTop: 12 }}>Executions</div><div className="dashboard-list" style={styles.list}>{executions.slice(-8).map((e, i) => <div key={i} className="dashboard-row" style={styles.row}><span>{e.track_id || e.exec_id || '-'}</span><span>{e.executed_price || '-'} × {e.executed_qty || 0}</span></div>)}{!executions.length && <div style={styles.muted}>체결 없음</div>}</div></Card>
    <Card title="Risk Snapshot" wide><div className="dashboard-metrics-grid" style={styles.metrics}><Metric label="Vol Spike" value={risk.is_vol_spike ? 'YES' : 'NO'} danger={risk.is_vol_spike} /><Metric label="Crisis" value={risk.is_crisis_regime ? 'YES' : 'NO'} danger={risk.is_crisis_regime} /><Metric label="Margin Diet" value={risk.is_margin_diet_required ? 'YES' : 'NO'} danger={risk.is_margin_diet_required} /><Metric label="Reason" value={risk.reason || 'NORMAL'} /></div></Card>
  </div>;
}
const styles = {
  grid: { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 14 }, card: { background: '#111827', border: '1px solid #334155', borderRadius: 14, padding: 16, minWidth: 0 }, cardTitle: { color: '#CBD5E1', fontSize: 12, fontWeight: 800, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 14 }, metrics: { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 10 }, metric: { display: 'flex', flexDirection: 'column', gap: 3, padding: 10, background: '#0F172A', borderRadius: 9 }, label: { color: '#64748B', fontSize: 10 }, controlRow: { display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 8 }, button: { border: '1px solid #475569', background: '#1E293B', color: '#E2E8F0', borderRadius: 8, padding: '8px 10px', cursor: 'pointer', fontSize: 11, fontWeight: 700 }, danger: { borderColor: '#7F1D1D', color: '#FCA5A5' }, list: { display: 'flex', flexDirection: 'column', gap: 5 }, row: { display: 'flex', justifyContent: 'space-between', gap: 10, padding: '7px 8px', background: '#0F172A', borderRadius: 7, fontSize: 10, color: '#CBD5E1' }, sectionLabel: { color: '#64748B', fontSize: 9, textTransform: 'uppercase', letterSpacing: '0.1em' }, muted: { color: '#64748B', fontSize: 12 },
};