import React, { useState } from 'react';
function Card({ title, children, wide = false }) { return <section className={`dashboard-card ${wide ? 'wide' : ''}`} style={{ ...styles.card, gridColumn: wide ? '1 / -1' : undefined }}><div style={styles.cardTitle}>{title}</div>{children}</section>; }
function Metric({ label, value, danger = false }) { return <div style={styles.metric}><span style={styles.label}>{label}</span><strong style={{ color: danger ? '#F87171' : '#F8FAFC' }}>{value}</strong></div>; }
function Button({ children, onClick, danger = false }) { return <button type="button" className="dashboard-btn" onClick={onClick} style={{ ...styles.button, ...(danger ? styles.danger : {}) }}>{children}</button>; }
export default function VirtualExchangePanel({ state, sendCommand }) {
  const market = state.market || {};
  const condition = state.marketCondition || {};
  const [price, setPrice] = useState(Number(market.price || 350));
  const [volatility, setVolatility] = useState(Number(condition.volatility_ratio || 1));
  const [spread, setSpread] = useState(Number(market.spread || 0.05));
  const [volume, setVolume] = useState(Number(market.volume || 1000));
  const command = (action, payload = {}) => sendCommand({ action, ...payload });
  const applyGenerator = () => command('set_market_generator', { base_price: Number(price), volatility_ratio: Number(volatility), spread: Number(spread), volume: Number(volume) });
  return <div className="dashboard-grid" style={styles.grid}>
    <Card title="Virtual Exchange Status"><div className="dashboard-metrics-grid" style={styles.metrics}><Metric label="KOSPI200" value={Number(market.price || 0).toFixed(2)} /><Metric label="Bid" value={Number(market.bid || 0).toFixed(2)} /><Metric label="Ask" value={Number(market.ask || 0).toFixed(2)} /><Metric label="Spread" value={Number(market.spread || 0).toFixed(4)} /><Metric label="Volume" value={Number(market.volume || 0).toLocaleString('ko-KR')} /><Metric label="Tick" value={market.seq_id || 0} /></div></Card>
    <Card title="Market Regime"><div className="dashboard-control-row" style={styles.controlRow}>{['NORMAL', 'BULL', 'BEAR', 'SIDEWAYS', 'VOLATILE', 'CRISIS'].map((regime) => <Button key={regime} danger={regime === 'CRISIS'} onClick={() => command('set_market_regime', { regime })}>{regime}</Button>)}</div><div className="dashboard-metrics-grid" style={styles.metrics}><Metric label="Current Regime" value={condition.regime || 'NEUTRAL'} danger={String(condition.regime).includes('CRISIS')} /><Metric label="Confidence" value={`${(Number(condition.regime_confidence || 0) * 100).toFixed(1)}%`} /><Metric label="Liquidity" value={condition.liquidity_level || 'NORMAL'} /><Metric label="Stress" value={`${(Number(condition.stress_level || 0) * 100).toFixed(1)}%`} danger={Number(condition.stress_level || 0) >= 0.7} /></div></Card>
    <Card title="Price / Data Generator" wide><div className="dashboard-form-grid" style={styles.formGrid}><label style={styles.field}>Base Price<input style={styles.input} type="number" value={price} onChange={(e) => setPrice(e.target.value)} /></label><label style={styles.field}>Volatility Ratio<input style={styles.input} type="number" step="0.1" value={volatility} onChange={(e) => setVolatility(e.target.value)} /></label><label style={styles.field}>Spread<input style={styles.input} type="number" step="0.01" value={spread} onChange={(e) => setSpread(e.target.value)} /></label><label style={styles.field}>Volume<input style={styles.input} type="number" value={volume} onChange={(e) => setVolume(e.target.value)} /></label></div><div className="dashboard-control-row" style={styles.controlRow}><Button onClick={applyGenerator}>가격 생성조건 적용</Button><Button onClick={() => command('set_simulation_runtime', { running: true })}>START</Button><Button onClick={() => command('set_simulation_runtime', { running: false })}>PAUSE</Button><Button onClick={() => command('reset_market_simulation')}>RESET</Button></div></Card>
    <Card title="Market Stress Injection"><div className="dashboard-control-row" style={styles.controlRow}><Button onClick={() => command('inject_market_stress', { type: 'VOL_SPIKE' })}>Vol Spike</Button><Button onClick={() => command('inject_market_stress', { type: 'LIQUIDITY_DROP' })}>Liquidity 감소</Button><Button onClick={() => command('inject_market_stress', { type: 'GAP' })}>Gap</Button><Button danger onClick={() => command('inject_market_stress', { type: 'CRASH' })}>Crash</Button><Button danger onClick={() => command('inject_market_stress', { type: 'FLASH_MOVE' })}>Flash Move</Button><Button onClick={() => command('clear_market_stress')}>Stress 해제</Button></div></Card>
    <Card title="Data Stream Control"><div className="dashboard-control-row" style={styles.controlRow}><Button onClick={() => command('set_tick_speed', { speed: 'SLOW' })}>SLOW</Button><Button onClick={() => command('set_tick_speed', { speed: 'NORMAL' })}>NORMAL</Button><Button onClick={() => command('set_tick_speed', { speed: 'FAST' })}>FAST</Button></div><div className="dashboard-metrics-grid" style={styles.metrics}><Metric label="Stress Flags" value={(condition.stress_flags || []).length} /><Metric label="Timestamp" value={condition.timestamp || market.timestamp || '-'} /></div></Card>
  </div>;
}
const styles = {
  grid: { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 14 }, card: { background: '#111827', border: '1px solid #334155', borderRadius: 14, padding: 16, minWidth: 0 }, cardTitle: { color: '#CBD5E1', fontSize: 12, fontWeight: 800, letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 14 }, metrics: { display: 'grid', gridTemplateColumns: 'repeat(2, minmax(0, 1fr))', gap: 10 }, metric: { display: 'flex', flexDirection: 'column', gap: 3, padding: 10, background: '#0F172A', borderRadius: 9 }, label: { color: '#64748B', fontSize: 10 }, controlRow: { display: 'flex', flexWrap: 'wrap', gap: 8, marginBottom: 8 }, button: { border: '1px solid #475569', background: '#1E293B', color: '#E2E8F0', borderRadius: 8, padding: '8px 10px', cursor: 'pointer', fontSize: 11, fontWeight: 700 }, danger: { borderColor: '#7F1D1D', color: '#FCA5A5' }, formGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 10, marginBottom: 12 }, field: { display: 'flex', flexDirection: 'column', gap: 5, color: '#94A3B8', fontSize: 10 }, input: { background: '#0F172A', color: '#F8FAFC', border: '1px solid #334155', borderRadius: 8, padding: 8, minWidth: 0, width: '100%' },
};